homepage:
  path: /
  controller: DefaultController::homeAction
  methods: [GET,POST]

notFound:
  path: /404
  controller: NotFoundController::notFound
  methods: [GET,POST]

blog:
  path: /blog
  controller: BlogController::blog
  methods: [GET,POST]

disconnected:
  path: /disconnected
  controller: DisconnectedController::disconnected
  methods: [GET,POST]

contact:
  path: /contact
  controller: ContactController::contact
  methods: [GET,POST]

newArticle:
  path: /newarticle
  controller: NewArticleController::newArticle
  methods: [GET,POST]

article:
  path: /article/{id}
  controller: ArticleController::article
  methods: [GET,POST]
  requirements:
    id: '\d+'

registration:
  path: /registration
  controller: RegistController::registAction
  methods: [GET,POST]

resume:
  path: /resume
  controller: ResumeController::resume
  methods: [GET,POST]
  requirements:

profil:
  path: /profil
  controller: ProfilController::profil
  methods: [GET,POST,DELETE]
  requirements:

connect:
  path: /connection
  controller: ConnectController::connect
  methods: [GET,POST]
  requirements:
