homepage:
  path: /
  controller: DefaultController::homeAction
  methods: [GET,POST]

resume:
  path: /resume/
  controller: DefaultController::resume
  methods: [GET,POST]

notFound:
  path: /404/
  controller: DefaultController::notFound
  methods: [GET,POST]

blog:
  path: /blog/
  controller: DefaultController::blog
  methods: [GET,POST]

portfolio:
  path: /portfolio/
  controller: DefaultController::portFolio
  methods: [GET,POST]

contact:
  path: /contact/
  controller: DefaultController::contact
  methods: [GET,POST]

registration:
  path: /registration/
  controller: DefaultController::registration
  methods: [GET,POST]

resumes:
  path: /resumes/
  controller: ResumeController::resumeAction
  methods: [GET,POST]
  requirements:
    id: '\d+'

connection:
  path: /connection/
  controller: DefaultController::connection
  methods: [GET,POST]