homepage:
  path: /
  controller: DefaultController::homeAction
  methods: [GET,POST]

resume:
  path: /resume/{id}
  controller: ResumeController::resumeAction
  methods: [GET,POST]
  requirements:
    id: '\d+'